# Generated by Django 6.0.7 on 2026-07-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_device_site'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='device',
            name='unique_ip_per_site',
        ),
        migrations.AddField(
            model_name='device',
            name='network',
            field=models.CharField(blank=True, help_text='Customer or Network name', max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(fields=('network', 'ip_address'), name='unique_ip_per_network'),
        ),
        migrations.RemoveField(
            model_name='device',
            name='site',
        ),
        migrations.DeleteModel(
            name='Site',
        ),
    ]
